### PR TITLE
Gemfile

### PR DESCRIPTION
**Pull request by gilesbowkett**
Added a Gemfile. now you can do

`gem install bundler && bundle && rake test`

and have a painless install (at least on OS X)

### CODE REVIEW

**Comment by automatthew** [comment]
Do any of the deps need to be listed in the Gemfile?  I thought we could point the Gemfile at the gemspec.

**Comment by gilesbowkett** [comment]
Well, a Gemfile like this:

``` ruby
source "https://rubygems.org"

gemspec
gem "starter"
```

is showing me errors like this:

`cannot load such file -- starter/tasks/gems/release`

which I wasn't getting from the Gemfile in 5d8ac61.

**Comment by gilesbowkett** [comment]
fixed in latest commit, I think.

pretty sure the problem is that the `starter` you get with `gem install` (or Bundler) is v0.1.10, but the `starter` in GitHub `master` is 0.2.0.

**Comment by automatthew** [comment]
ah.  We probably need both "starter/gems" and "starter/gems/release".  I separated them so that Ruby projects that you don't release as rubygems don't have the release task.

**Comment by gilesbowkett** [comment]
well, I think it's either accept 23e07a6 or push starter 0.2 to rubygems.org.

**Comment by gilesbowkett** [comment]
OK, so that was wrong. but:

```
Bundler could not find compatible versions for gem "hashie":
  In Gemfile:
    patchboard (>= 0) ruby depends on
      hashie (~> 2.0) ruby

    starter (~> 0.2.1) ruby depends on
      ghee (~> 0.9.11) ruby depends on
        hashie (1.2.0)
```

**Comment by gilesbowkett** [comment]
so...

**Pull request closed without merging**
