### PR TITLE
fix to pass request body to authorizer

### PR DESCRIPTION
**Pull request by jvergeldedios**
We have a need for using the request body in the authorizer method to do things like hashing and signing in the authorization header.

### CODE REVIEW

**Comment by automatthew** [comment]
@jvergeldedios  It's a worthy feature, but I think the authorizer method should now take keyword args (a Hash, in Ruby) rather than 4 positional args.

``` ruby
context.authorizer(
  :schemes => @auth_schemes,
  :resource => resource, :action => @name,
  :request => input_options
)
```

I'm okay with the rescue hack for the 0.5.x series of Patchboard.

**Comment by jvergeldedios** [comment]
@automatthew Agreed, whenever you are going to release 0.6.0 the interface for authorizer should only support the named args signature. Should I add that option now with the hack for backwards compatibility, or do you want to wait until you have more breaking changes to release?

**Comment by automatthew** [comment]
0.5 is already sort of chaotically transitional.  Add named args and the hack, and I'll release a patch version.

**Comment by jvergeldedios** [comment]
@automatthew Updated.

**Pull request merged**
